#include<stdio.h>
main()
{
	remove("firstrun");
	remove("csestudents.bin");
	remove("ecestudents.bin");
	remove("cseteachers.bin");
	remove("eceteachers.bin");
	remove("applicants.bin");
	remove("tcse.bin");
	remove("tece.bin");
}